[template.environment]
  GQL_HOST = "https://dev.swetasboutique.com/graphql"
  NUXT_IMAGE_DOMAINS = "dev.swetasboutique.com"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://secure.woonuxt.com/.*"]
